Insert Into TMPSE5 Select E5_FILIAL ,
E5_NUMERO ,
E5_PREFIXO ,
E5_PARCELA ,
E5_TIPO ,
E5_CLIFOR ,
E5_LOJA ,
E5_DOCUMEN ,
E5_DATA ,
E5_VALOR,
E5_TIPODOC,
E5_SEQ,
E5_NATUREZ,
E5_DTDIGIT,
E5_HISTOR,
E5_VRETPIS,
E5_VRETCOF,
E5_VRETCSL,
E5_VRETIRF,
E5_VRETISS,
'GFDGFDG' FS_CHAVE
From SE5990 E5 WITH (NOLOCK)
 Where SUBSTRING(E5_FILIAL, 1, 2) = '03'
 AND E5_CLIFOR BETWEEN '      ' AND 'zzzzzz'
 AND E5_NUMERO BETWEEN '         ' AND 'zzzzzzzzz'
 AND E5_PREFIXO BETWEEN '   ' AND 'zzz'
 AND E5_TIPODOC NOT IN ('TE', 'TR', 'JR', 'DC')
 AND E5_SITUACA<>'C'
 AND E5.D_E_L_E_T_ = ' '
 AND E5_DATA Between '20171001' and '20171031' AND E5_RECPAG = 'P' AND E5_MOTBX IN ('DEB', 'NOR') AND
 NOT EXISTS (SELECT E5_NUMERO FROM SE5990 SE5
 	WHERE 
	SE5.E5_FILIAL=E5.E5_FILIAL
 	AND SE5.D_E_L_E_T_ = ' '
 	AND SE5.E5_PREFIXO=E5.E5_PREFIXO
 	AND SE5.E5_NUMERO=E5.E5_NUMERO
 	AND SE5.E5_PARCELA=E5.E5_PARCELA
 	AND SE5.E5_TIPO=E5.E5_TIPO
 	AND SE5.E5_CLIFOR=E5.E5_CLIFOR
 	AND SE5.E5_LOJA=E5.E5_LOJA
 	AND SE5.E5_TIPODOC='ES'
 	AND SE5.E5_SEQ=E5.E5_SEQ)